### ISSUE TITLE
[Setting] github 초기 세팅 

### ISSUE THREAD

**Issue by SongJwans** [Estsoft-Udon/ClassicJeans#1]
### ✏이슈 설명

- 프로젝트 시작 전 github 초기 설정하기
***
### ✅구현 내용
- [x]  Default branch : develop으로 변경
- [x]  public rulesets 생성
*** 
### 🎻기타

- 청바지 화이팅!🎉

**Comment by SangWon-Lee1** [comment]
이슈템플릿 완성 수정해주세요
