### ISSUE TITLE
[FEAT/FIX/REFACTOR] 프론트 수정 / hospital 코드 정리

### ISSUE THREAD

**Issue by jeongggggg** [Estsoft-Udon/ClassicJeans#123]
### ✏이슈 설명

- 아래로 스크롤 해주세요 모니터 비율별로 위치가 다르게 보이는 부분 수정
- 마이페이지, 가족 정보 -> 연동된 가족 정보 없을 때 프론트 텍스트 및 비율 수정
- 공공의료기관 코드 리팩토링
***
### ✅구현 내용

- [x] 아래로 스크롤 해주세요 모니터 비율별로 위치가 다르게 보이는 부분 수정
- [x] 마이페이지, 가족 정보 -> 연동된 가족 정보 없을 때 프론트 텍스트 및 비율 수정
- [x] 공공의료기관 코드 리팩토링
- [x] 검색취소 추가
- [x] 메인제외 스크롤탑버튼 추가
- [x] 병원예약 form
- [x] 예약 관련 관리자 추가
- [x] 공공의료기관 지도 API 에러 수정 -> 새로 추가한 데이터가 db에 잘못들어가 있었음
***
### 🎻기타

처음부터 깔끔하게 코드 작성할껄... 너무 많은 길을 와버렸습니다

**Comment by jingun0516** [comment]
여기 투두가 계속 늘어나네요?
