### ISSUE TITLE
[Design-system] 기능 명세서 작성

### ISSUE THREAD

**Issue by SangWon-Lee1** [Estsoft-Udon/ClassicJeans#3]
### ✏설명

- 프로젝트에 추가할 기능
***
### ✅구현 내용

- [ ] 기능 명세서 작성
***
### 🎻기타

- https://www.notion.so/oreumi/cc4079b6409c4ea9b9ce336d385ba51c

**Comment by SongJwans** [comment]
기능 명세 너무 어렵네요..
