### ISSUE TITLE
[FIX / DESIGN] 리스트 페이지 디자인 수정, 공공의료기관 병원명 검색 기능 추가

### ISSUE THREAD

**Issue by jeongggggg** [Estsoft-Udon/ClassicJeans#72]
### ✏이슈 설명

- 요양원, 복지시설 리스트 검색 부분 스타일 수정
- 공공의료기관 페이지네이션 수정
- 병원명 검색 기능 추가
***
### ✅구현 내용

- [x] 요양원, 복지시설 리스트 검색 부분 스타일 수정
- [x] 공공의료기관 페이지네이션 수정
- [x] 병원명 검색 기능 추가
***

**Comment by jingun0516** [comment]
디자인 기대됩니다

**Comment by jeongggggg** [comment]
> 디자인 기대됩니다

네..? 땀납니다
